/** Generate the deterministic visual-function inventory from the TS registry. */

import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import {
  CAPABILITIES,
  VISUAL_FUNCTION_REGISTRY_VERSION,
  type Capability,
} from '../shared/registry.ts';

function countBy(values: readonly string[]): Record<string, number> {
  const counts = new Map<string, number>();
  for (const value of values) counts.set(value, (counts.get(value) ?? 0) + 1);
  return Object.fromEntries(Array.from(counts.entries()).sort(([a], [b]) => a.localeCompare(b)));
}

function markdownCell(value: unknown): string {
  return String(value ?? '')
    .replace(/\|/g, '\\|')
    .replace(/\r?\n/g, ' ');
}

function statusOf(capability: Capability): string {
  return capability.implemented ? 'implemented' : 'documented-only';
}

const functions = [...CAPABILITIES].sort((a, b) => a.type.localeCompare(b.type));
const implemented = functions.filter((capability) => capability.implemented).length;
const summary = {
  total: functions.length,
  implemented,
  documentedOnly: functions.length - implemented,
  aliases: functions.filter((capability) => capability.aliasOf).length,
  byDomain: countBy(functions.map((capability) => capability.domain)),
  byCategory: countBy(functions.map((capability) => capability.category)),
  byRenderer: countBy(functions.map((capability) => capability.renderer)),
  byStatus: countBy(functions.map(statusOf)),
};

const inventory = {
  schemaVersion: VISUAL_FUNCTION_REGISTRY_VERSION,
  summary,
  functions,
};

const markdown: string[] = [
  '# NEMO Visual Function Inventory',
  '',
  '<!-- Generated by `npm run visual:functions`; do not edit by hand. -->',
  '',
  `Registry schema version: \`${VISUAL_FUNCTION_REGISTRY_VERSION}\``,
  '',
  `- Total functions: ${summary.total}`,
  `- Implemented: ${summary.implemented}`,
  `- Documented only: ${summary.documentedOnly}`,
  `- Aliases: ${summary.aliases}`,
  '',
  '## Functions by domain',
  '',
  '| Domain | Count |',
  '| --- | ---: |',
  ...Object.entries(summary.byDomain).map(([name, count]) => `| ${markdownCell(name)} | ${count} |`),
  '',
  '## Functions by category',
  '',
  '| Category | Count |',
  '| --- | ---: |',
  ...Object.entries(summary.byCategory).map(
    ([name, count]) => `| ${markdownCell(name)} | ${count} |`
  ),
  '',
  '## Function inventory',
  '',
  '| Function | Domain | Category | Renderer | Implementation file | Tests | Status |',
  '| --- | --- | --- | --- | --- | --- | --- |',
  ...functions.map((capability) =>
    [
      `| \`${markdownCell(capability.type)}\``,
      markdownCell(capability.domain),
      markdownCell(capability.category),
      markdownCell(capability.renderer),
      markdownCell(capability.implementation.file ?? '—'),
      `${markdownCell(capability.test.file)} (${markdownCell(capability.test.status)})`,
      `${markdownCell(statusOf(capability))} |`,
    ].join(' | ')
  ),
  '',
];

const projectRoot = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const docsDirectory = resolve(projectRoot, 'docs');
const jsonPath = resolve(docsDirectory, 'visual-functions.json');
const markdownPath = resolve(docsDirectory, 'visual-functions.md');

mkdirSync(docsDirectory, { recursive: true });
writeFileSync(jsonPath, `${JSON.stringify(inventory, null, 2)}\n`, 'utf8');
writeFileSync(markdownPath, `${markdown.join('\n')}\n`, 'utf8');

console.log(`NEMO visual functions (registry ${VISUAL_FUNCTION_REGISTRY_VERSION})`);
console.log(`Total functions: ${summary.total}`);
console.log(`Implemented: ${summary.implemented}`);
console.log(`Documented only: ${summary.documentedOnly}`);
console.log('Functions by domain:');
for (const [domain, count] of Object.entries(summary.byDomain)) {
  console.log(`  ${domain}: ${count}`);
}
console.log('Functions by category:');
for (const [category, count] of Object.entries(summary.byCategory)) {
  console.log(`  ${category}: ${count}`);
}
console.log(`Generated: ${jsonPath}`);
console.log(`Generated: ${markdownPath}`);
